export  const PowerStationActionTypes = {
    INIT_POWERSTATIONS             :   'INIT_POWERSTATIONS',
    SELECT_POWERSTATION            :   'SELECT_POWERSTATION',
    REMOVE_SELECTED_POWERSTATION   :   'REMOVE_SELECTED_POWERSTATION',
    DELETE_POWERSTATION            :   'DELETE_POWERSTATION',
    UPDATE_POWERSTATION            :   'UPDATE_POWERSTATION',
    INSERT_POWERSTATION            :   'INSERT_POWERSTATION'
}
